version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: ${APPLICATION_IMAGE_NAME}
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: