
    create table table_course (
        created_at timestamp(6),
        id uuid not null,
        name varchar(255),
        primary key (id)
    );

    create table table_enrolled_course (
        final_grade float(53) not null,
        finish_date date,
        start_date date,
        id bigint generated by default as identity,
        course_id uuid,
        student_id uuid,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','DROPPED')),
        primary key (id)
    );

    create table table_enrolled_project (
        finish_date date,
        start_date date,
        id bigint generated by default as identity,
        project_id uuid,
        student_id uuid,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','DROPPED')),
        primary key (id)
    );

    create table table_project (
        created_at timestamp(6),
        id uuid not null,
        category varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table table_student (
        created_at timestamp(6),
        updated_at timestamp(6),
        id uuid not null,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists table_enrolled_course 
       add constraint FKgcrcap030yd8rqpyoxfttnceq 
       foreign key (course_id) 
       references table_course;

    alter table if exists table_enrolled_course 
       add constraint FKkaftwvhsxleogrnw27e5x4jbt 
       foreign key (student_id) 
       references table_student;

    alter table if exists table_enrolled_project 
       add constraint FKlfy5pa5yxmkvk3mbhvaq5pd4y 
       foreign key (project_id) 
       references table_project;

    alter table if exists table_enrolled_project 
       add constraint FK22p0mq49khlrb1w05yrt6o4wh 
       foreign key (student_id) 
       references table_student;
