pipeline {
    agent {
        label 'linux' || 'windows'
    }
    environment {
        PORT = 9090
        APPLICATION_IMAGE_NAME = 'ac2_api'
        POSTGRES_USER = credentials('POSTGRES_USER')
        POSTGRES_PASSWORD = credentials('POSTGRES_PASSWORD')
        POSTGRES_DB = credentials('POSTGRES_DATABASE')
    }
    stages {
        stage('Verify tooling...') {
            steps {
                checkout scm
                script {
                    if (isUnix()) {
                        sh './shell/checkout.sh'
                    } else {
                        bat 'bat/checkout.bat'
                    }
                }
            }
        }
        stage('Prune Docker Data') {
            steps {
                script {
                    if(isUnix()) {
                        sh './shell/clear.sh'
                    } else {
                        bat 'bat/clear.bat'
                    }
                }
            }
        }
        stage('Start Container') {
            steps {
                script {
                    if(isUnix()) {
                        sh './shell/compose.sh'
                    } else {
                        bat 'bat/compose.bat'
                    }
                }
            }
        }
        stage('Run tests') {
            steps {
                script {
                    if(isUnix()) {
                        sh './shell/test.sh'
                    } else {
                        bat 'bat/test.bat'
                    }
                }
            }
        }
    }
}